"""
평가용 Ground Truth 레이블.

각 쿼리에 대해 관련 있다고 판단된 (book_id, 제목) 쌍의 목록.
- 교차언어(cross-lingual) 쿼리: 해당 저자의 작품이나 그 저자를 주로 다루는 비평서
- 내용/주제(content) 쿼리: 해당 주제에 명백히 해당하는 도서

Recall@K = (K개 결과 중 LABELS에 있는 도서 수) / len(LABELS[query])
"""
from __future__ import annotations

LABELS: dict[str, list[tuple[int, str]]] = {

    # ──────────────────────────────────────────
    # 교차언어(Cross-lingual) 쿼리
    # ──────────────────────────────────────────

    "토마스 만": [
        (471, "Buddenbrooks"),
        (472, "Lotte in Weimar"),
        (473, "Die Erzählungen Band 1"),
        (474, "Die Erzählungen Band 2"),
        (475, "Der Zauberberg 1"),
        (476, "Der Zauberberg 2"),
        (477, "Mario und der Zauberer"),
        (767, "Interpretationen Th.Mann Romane und Erzählungen"),
        (852, "Tristan"),
        (952, "Tristan"),
        (989, "Mario und der Zauberer"),
        (1005, "Tonio Kröger"),
        (1031, "Der Tod in Venedig"),
        (1297, "Der Zauberberg"),
        (1298, "Der Erwählte / Felix Krull"),
        (1299, "Doktor Faustus"),
        (1300, "Joseph und seine Brüder 1"),
        (1301, "Joseph und seine Brüder 2"),
        (1302, "Buddenbrooks"),
        (1303, "Königliche Hoheit/Lotte in Weimar"),
        (1549, "Doktor Faustus"),
        (1634, "Thomas Mann"),
        (1672, "Thomas Mann"),
        (1687, "Thomas Mann"),
        (1902, "Thomas Mann"),
        (1994, "100 Jahre Thomas Mann bei S.Fischer"),
        (1995, "Thomas Mann Leben und Werk"),
        (1996, "Buddenbrooks I"),
        (1997, "Buddenbrooks II"),
        (1998, "Thomas Mann Leben und Werk"),
        (2349, "현실주의 독일문학"),
        (2482, "Über deutsche Literatur"),
        (4117, "Thomas-Mann-Handbuch"),
    ],

    "브레히트": [
        (4, "Gesammelte Gedichte Band I"),
        (333, "Erinnerung an Brecht"),
        (377, "브레히트의 연극이론"),
        (410, "Und sagte kein einziges Wort"),
        (411, "Der böse Baal der asoziale"),
        (412, "Gedichte"),
        (427, "Deutschland, Deutschland, über alles"),
        (446, "Brechts Antigone des Sophokles"),
        (743, "Brechts Dramen"),
        (1086, "Der gute Mensch von Sezuan"),
        (1088, "Der gerechte Krieg"),
        (1089, "Der kaukasische Kreidekreis"),
        (1090, "Galilei"),
        (1662, "Brecht"),
        (2040, "Bertolt Brecht"),
        (2043, "Die deutsche Ballade von Bürger bis Brecht"),
        (2082, "Die Dreigroschenoper"),
        (2087, "Bertolt Brecht"),
        (2247, "Bertoltbrecht"),
        (3350, "Bertolt Brecht und sein Verhältnis zur chinesischen"),
        (3574, "Stücke"),
        (3629, "브레히트와 현대연극 제 19집"),
        (3630, "브레히트와 현대연극 제 34집"),
        (3631, "브레히트와 현대연극 제 39집"),
        (4123, "청년 브레히트 '혁명을 꿈꾸다'"),
    ],

    "괴테": [
        (282, "괴테와 동양 사상"),
        (283, "에커만, 괴테와의 대화"),
        (285, "괴테와 독일 고전주의"),
        (288, "괴테의 파우스트와 그 문학 세계 1"),
        (393, "Fischer Goethe-Wortschatz"),
        (394, "Lexikon der Goethe Zitate"),
        (432, "Italienische Reise"),
        (433, "Verweile Doch"),
        (434, "Goethe Novelle"),
        (435, "Goethe Gedichte"),
        (436, "Goethe Elegie von Marienbad"),
        (531, "Die deutsche Novelle von Goethe bis Kafka"),
        (623, "Egmont"),
        (626, "Hermann und Dorothea"),
        (643, "Briefe an ihren Sohn Johann Wolfgang"),
        (663, "Gespräche mit Goethe"),
        (679, "Kommentar zu Goethes Faust"),
        (688, "Aus meinem Leben Dichtung und Wahrheit 1"),
        (689, "Aus meinem Leben Dichtung und Wahrheit 2"),
        (690, "Goethe-Bibliographie"),
        (691, "Goethe-Bibliographie"),
        (692, "Die Wahlverwandtschaften"),
        (693, "Egmont"),
        (694, "Götz von Berlichingen"),
        (695, "Iphigenie auf Tauris"),
        (696, "Das Märchen"),
        (697, "Torquato Tasso"),
        (698, "Urfaust"),
        (699, "Urfaust"),
        (700, "Wilhelm Meisters Lehrjahre"),
        (756, "Goethes Dramen"),
        (757, "Goethes Dramen"),
        (758, "Goethes Erzählwerk"),
        (942, "Die Leiden des jungen Werther"),
        (953, "Götz von Berlichingen"),
        (964, "Egmont"),
        (973, "Iphigenie auf Tauris"),
        (988, "Torquato Tasso"),
        (995, "Die Wahlverwandtschaften"),
        (1000, "Novelle"),
        (1001, "Novelle"),
        (1002, "Wilhelm Meisters Lehrjahre"),
        (1036, "Urfaust"),
        (1093, "Faust - Erster und Zweiter Teil"),
        (1094, "Die Leiden des jungen Werther"),
        (1108, "Faust"),
        (1229, "Johann Wolfgang Goethe Faust Texte"),
        (1230, "Johann Wolfgang Goethe Faust Kommentare"),
        (1231, "Johann Wolfgang Goethe Wilhelm Meisters Wanderjahre"),
        (1232, "Johann Wolfgang Goethe Wilhelm Meisters Theatralische Sendung"),
        (1233, "J.W.Goethe Faust volume seconde"),
        (1234, "J.W.Goethe Faust volume primo"),
        (1235, "Gedichte und Epen 1"),
        (1236, "Gedichte und Epen 2"),
        (1237, "Dramatische Dichtungen 1"),
        (1238, "Dramatische Dichtungen 2"),
        (1239, "Dramatische Dichtungen 3"),
        (1240, "Romane und Novellen 1"),
        (1241, "Romane und Novellen 2"),
        (1242, "Romane und Novellen 3"),
        (1243, "Autobiographische Schriften 1"),
        (1244, "Autobiographische Schriften 2"),
        (1245, "Autobiographische Schriften 3"),
        (1246, "Schriften zur Kunst und Literatur"),
        (1247, "Naturwissenschaftliche Schriften 1"),
        (1248, "Naturwissenschaftliche Schriften 2"),
        (1249, "Goethe *"),
        (1250, "Goethe **"),
        (1251, "Goethe ***"),
        (1617, "Gedichte Versepen"),
        (1618, "Dramen.Novellen"),
        (1619, "Faust1 und 2 Wahlverwandtschaften"),
        (1620, "Werther Lehrjahre"),
        (1621, "Dichtung und Wahrheit"),
        (1622, "Vermischte Schriften"),
        (1653, "Goethes Faust im Blickfeld des XX.Jahrhunderts"),
        (1660, "Aufsätze zu Goethes Faust"),
        (1664, "Das Goethebild des 20.Jahrhunderts"),
        (1712, "Die Wahlverwandtschaften"),
        (1931, "Goethes Faust"),
        (1932, "Aufsätze zu Goethes Faust I"),
        (1933, "Aufsätze zu Goethes Faust II"),
        (1934, "Goethe-Jahrbuch"),
        (1935, "Goethe"),
        (1936, "Die Astrologie in Goethes Weltschau"),
        (1937, "Deutsche Revolutionsdramatik seit Goethe"),
        (1938, "Goethes Geheimes Vermächtnis"),
        (1939, "Goethe-Parodien"),
        (1940, "Zum Thema: Goethe"),
        (1941, "Johann Wolfgang Goethe"),
        (1942, "Goethe im zwanzigsten Jahrhundert"),
        (1943, "Goethe: Ein Versuch über den Erfolg"),
        (1944, "Geschichte der deutschen Lyrik von Goethe bis Heine 1"),
        (1945, "Geschichte der deutschen Lyrik von Goethe bis Heine 2"),
        (1946, "Geschichte der deutschen Lyrik von Goethe bis Heine 3"),
        (1947, "Mit Goethe durch das Jahr"),
        (1948, "Goethe in Leipzig"),
        (1949, "Johann Wolfgang von Goethe der mentor"),
        (1950, "Griechentum und Goethezeit"),
        (1951, "Goethe - ein letztes Universalgenie?"),
        (1952, "Goethe Leben und Werk"),
        (2051, "Die DEUTSCHE Novelle von Goethe bis Kafka"),
        (2341, "나의 인생 「시와 진실」"),
        (2380, "영화로 읽는 독일 및 독일인들1"),
        (2381, "잠언과 성찰"),
        (2382, "괴테의 여우 라이네케"),
        (2383, "괴테 시선 2"),
        (2384, "괴테 시선 2"),
        (2385, "괴테 시선 3"),
        (2386, "헤르만과 도로테아"),
        (2389, "하이너 뮐러 문학의 이해"),
        (2390, "괴테 시선 Ⅳ - 크세니엔"),
        (2424, "Romane und Novellen 1"),
        (2432, "Die deutsche Novelle"),
        (2594, "Die Leiden des jungen Werther Novelle"),
        (2595, "젊은 베르테르의 슬픔"),
        (2596, "젊은 베르테르의 슬픔"),
        (2600, "Iphigenie Auf Tauris Torquato Tasso"),
        (2601, "Iphigenie Auf Tauris Torquato Tasso"),
        (2602, "Gespräch mit Goethe"),
        (2604, "Die dramatische Einheit von Goethes Faust"),
        (2871, "Jahrbuch 1969 / Goethe-Institut"),
        (3305, "파우스트"),
        (3309, "파우스트"),
        (3314, "Faust - Annäherung an einen Mythos"),
        (3315, "Goethe in der Kunst des 20.Jahrhunderts"),
        (3316, "Goethe Faust Zweiter Teil"),
        (3317, "Faust - Der Tragödie zwiter Teil"),
        (3319, "Goethe - Der zeichner und maler"),
        (3320, "Gustaf Gründgens Faust in Bildern"),
        (3354, "Faust"),
        (3359, "Königs Erläuterungen zu Goethe Faust"),
        (3367, "Erläuterungen zu Goethes Faust Teil2"),
        (3368, "Erläuterungen zu Goethes Faust Teil1"),
        (3374, "Das Volksbuch von Doktor Faust"),
        (3376, "Armin Müller-Stahl, Urfaust"),
        (3377, "Goethe & Rembrandt"),
        (3405, "Ontologie und Geschichte in Goethes Faust"),
        (3458, "Who is who in Goethes Faust?"),
        (3481, "괴테와 괴테 문학의 의의"),
        (3484, "괴테와 융 파우스트의 분석심리학적 이해"),
        (3485, "괴테 사전"),
        (3486, "괴테 연구"),
        (3487, "파우스트와 빌헬름 마이스터 연구"),
        (3489, "파우스트 연구"),
        (3492, "괴테의 원형 파우스트 & 뷔히너의 보이첵"),
        (3952, "Goethes Mutter"),
    ],

    "히틀러": [
        (83, "Die Deutsche Sprache"),
        (84, "Zeitung Deutsch"),
        (85, "Zeitung Deutsch"),
        (263, "나의 투쟁 상"),
        (264, "나의 투쟁 하"),
        (371, "현대 독일문학 비평"),
        (2357, "히틀러는 아직도 살아있다"),
        (4045, "Von Caligari zu Hitler"),
        (4169, "Adi: Jugend eines Diktators"),
        (4204, "Hitlers Spionin"),
    ],

    "귄터 그라스": [
        (261, "양철북"),
        (262, "양철북"),
        (437, "Die Blechtrommel. Danziger Trilogie 1"),
        (438, "Die Blechtrommel. Danziger Trilogie 2"),
        (1323, "Günter Grass Werke 1"),
        (1324, "Günter Grass Werke 2"),
        (1325, "Günter Grass Werke 3"),
        (1326, "Günter Grass Werke 4"),
        (1327, "Günter Grass Werke 5"),
        (1328, "Günter Grass Werke 6"),
        (1329, "Günter Grass Werke 7"),
        (1330, "Günter Grass Werke 8"),
        (1331, "Günter Grass Werke 9"),
        (1332, "Günter Grass Werke 10"),
    ],

    "베를린 장벽": [
        (2324, "329일 베를린장벽 붕괴에서 독일통일까지"),
        (3254, "Ein Loch in der Mauer"),
        (3932, "Die Eiserne Mauer"),
    ],

    "헤르만 헤세": [
        (256, "유리알유희"),
        (450, "Geschichten aus dem Mittelalter"),
        (759, "Interpretationen Hesse Romane"),
        (760, "Interpretationen Hesse Romane"),
        (1019, "Der Steppenwolf"),
        (1020, "Unterm Rad"),
        (1026, "Der Erwarten"),
        (1027, "Der Steppenwolf"),
        (1029, "Siddharta"),
        (1304, "Peter Camenzind Unterm Rad"),
        (1305, "Gertrud Roßhalde"),
        (1306, "Demian Wanderung"),
        (1307, "Der Steppenwolf"),
        (1308, "Narziß und Goldmund"),
        (1309, "Das Glasperlenspiel I"),
        (1310, "Das Glasperlenspiel II"),
        (1311, "Hermann Hesse Erzählungen 1"),
        (1312, "Hermann Hesse Erzählungen 2"),
        (1313, "Hermann Hesse Erzählungen 3"),
        (1314, "Hermann Hesse Erzählungen 4"),
        (1315, "Hermann Hesse Erzählungen 5"),
        (1316, "Hermann Hesse Erzählungen 6"),
        (1317, "Hesse Sein Leben in Bildern und Texten"),
        (1318, "Hesse Werk und Wirkungsgeschichte"),
        (1640, "Novellen der Nobelpreistraeger"),
        (1641, "Narziss und Goldmund"),
        (1688, "Hermann Hesse A Pictorial Biography"),
        (2053, "Hermann Hesse Eine Chronik in Bildern"),
        (2085, "Hermann Hesse"),
        (2426, "Gesammelte Werke 8: Narziß und Goldmund"),
        (2451, "헤르만 헤세와의 만남"),
        (2477, "Die Romane und die großen Erzählungen"),
        (2542, "Hermann Hesse Gesammelte Werke 1"),
        (2543, "Hermann Hesse Gesammelte Werke 2"),
        (2544, "Hermann Hesse Gesammelte Werke 3"),
        (2545, "Hermann Hesse Gesammelte Werke 4"),
        (2546, "Hermann Hesse Gesammelte Werke 6"),
        (2547, "Hermann Hesse Gesammelte Werke 7"),
        (2548, "Hermann Hesse Gesammelte Werke 9"),
        (2549, "Hermann Hesse Gesammelte Werke 10"),
        (2550, "Hermann Hesse Gesammelte Werke 11"),
        (2551, "Hermann Hesse Gesammelte Werke 12"),
        (2647, "Hermann Hesse"),
        (2762, "헤세연구 Hesse-Forschung 제2집"),
        (2763, "헤세연구 Hesse-Forschung 제3집"),
        (2764, "헤세연구 Hesse-Forschung 제4집"),
        (2765, "헤세연구 Hesse-Forschung 제6집"),
        (2766, "헤세연구 Hesse-Forschung 제7집"),
        (2767, "헤세연구 Hesse-Forschung 제8집"),
        (2768, "헤세연구 Hesse-Forschung 제9집"),
        (2769, "헤세연구 Hesse-Forschung 제10집"),
        (2770, "헤세연구 Hesse-Forschung 제12집"),
        (2771, "헤세연구 Hesse-Forschung 제13집"),
        (2772, "헤세연구 Hesse-Forschung 제14집"),
        (2773, "헤세연구 Hesse-Forschung 제15집"),
        (2774, "헤세연구 Hesse-Forschung 제16집"),
        (2775, "헤세연구 Hesse-Forschung 제17집"),
        (2776, "헤세연구 Hesse-Forschung 제18집"),
        (2777, "헤세연구 Hesse-Forschung 제19집"),
        (2778, "헤세연구 Hesse-Forschung 제20집"),
        (2779, "헤세연구 Hesse-Forschung 제21집"),
        (2780, "헤세연구 Hesse-Forschung 제22집"),
        (2781, "헤세연구 Hesse-Forschung 제23집"),
        (2782, "헤세연구 Hesse-Forschung 제24집"),
        (2783, "헤세연구 Hesse-Forschung 제25집"),
        (2784, "헤세연구 Hesse-Forschung 제26집"),
        (2785, "헤세연구 Hesse-Forschung 제27집"),
        (2786, "헤세연구 Hesse-Forschung 제28집"),
        (3295, "크눌프, 데미안"),
        (3297, "꿈이 내 문을 두드릴 때"),
        (3300, "헤르만 헤세와의 만남"),
        (3303, "헤르만 헤세의 진실"),
        (3308, "Herman Hesses Steppenwolf"),
        (3312, "헤르만 헤세 - 모든 시작은 신비롭다"),
        (3339, "Stunden im Garten, Zwei Idyllen"),
        (3340, "Meine Glaube"),
        (3341, "Lektüre für Minuten"),
        (3342, "Die Welt der Bücher"),
        (3345, "Lektüre für Minuten"),
        (3347, "Eine Literaturgeschichte in Rezensionen und Aufsätzen 1"),
        (3348, "Eine Literaturgeschichte in Rezensionen und Aufsätzen 2"),
        (3349, "Kleine Freuden"),
        (3351, "Materialien zu Hermann Hesses Das Glasperlenspiel 1"),
        (3352, "Briefe an Freunde"),
        (3353, "Materialien zu Hermann Hesses Das Glasperlenspiel 2"),
        (3355, "Hermann-Hesse-Bibliographie"),
        (3356, "Wer lieben kann, ist glücklich"),
        (3357, "Hesse Kommentar"),
        (3358, "Königs Erläuterungen Hermann Hesse"),
        (3360, "Hermann Hesse Politik des Gewissens"),
        (3365, "Über Hermann Hesse (Zweiter Band)"),
        (3369, "Königs Erläuterungen Hermann Hesse 2"),
        (3373, "Hermann Hesse Briefe"),
        (3388, "Hermann Hesse Gesammelte Erzählungen Band1"),
        (3389, "Hermann Hesse Gesammelte Erzählungen Band2"),
        (3390, "Hermann Hesse Gesammelte Erzählungen Band3"),
        (3391, "Hermann Hesse Gesammelte Erzählungen Band4"),
        (3392, "Hermann Hesse Gesammelte Erzählungen Band5"),
        (3393, "Hermann Hesse Gesammelte Erzählungen Band6"),
        (3400, "Mystische Elemente aus West und Ost im Werk Hesses"),
        (3408, "Das Todesproblem bei Hermann Hesse"),
        (3418, "Zwischen Eigen-Sinn und Anpassung"),
        (3419, "Wege zu Hermann Hesse"),
        (3449, "Begegnungen mit Hermann Hesse"),
        (3453, "Hermann Hesse und seine literarischen Zeitgenossen"),
        (3454, "Hermann Hesse, als religiöser Mensch"),
        (3455, "Hermann Hesse Dichtung und Gedanke"),
        (3456, "Zen"),
        (3462, "Hermann Hesse und die Religion"),
        (3463, "Hermann Hesse - Peter Suhrkamp Briefwechsel"),
        (3468, "Briefe"),
        (3470, "Hesse kennen lernen"),
        (3471, "Hermann Hesse"),
        (3472, "Hermann Hesse"),
        (3473, "Hermann Hesse"),
        (3475, "Die Gedichte 1"),
        (3476, "Die Gedichte 2"),
        (3478, "Hermann Hesse, Seine Zeit im Engadin"),
        (3479, "In sight of chaos"),
        (3494, "환상동화집"),
        (3538, "Kunst als Therapie. Hermann Hesse und die Psychoanalyse"),
        (3539, "Farbe ist Leben"),
        (3540, "Freude am Garten"),
        (3541, "Interpretationen Hermann Hesse Romane"),
        (3542, "Hermann Hesse"),
        (3896, "Der Steppenwolf"),
        (375, "번역과 한국의 근대"),
    ],

    "독일문화원": [
        (371, "현대 독일문학 비평"),
        (2871, "Jahrbuch 1969 / Goethe-Institut"),
    ],

    "파우스트": [
        (288, "괴테의 파우스트와 그 문학 세계 1"),
        (679, "Kommentar zu Goethes Faust"),
        (698, "Urfaust"),
        (699, "Urfaust"),
        (792, "Fausts Leben, Taten und Höllenfahrt"),
        (1036, "Urfaust"),
        (1083, "Faust I-II"),
        (1093, "Faust - Erster und Zweiter Teil"),
        (1108, "Faust"),
        (1229, "Johann Wolfgang Goethe Faust Texte"),
        (1230, "Johann Wolfgang Goethe Faust Kommentare"),
        (1233, "J.W.Goethe Faust volume seconde"),
        (1234, "J.W.Goethe Faust volume primo"),
        (1299, "Doktor Faustus"),
        (1549, "Doktor Faustus"),
        (1619, "Faust1 und 2 Wahlverwandtschaften"),
        (1653, "Goethes Faust im Blickfeld des XX.Jahrhunderts"),
        (1660, "Aufsätze zu Goethes Faust"),
        (1706, "Faust Eine Einführung"),
        (1931, "Goethes Faust"),
        (1932, "Aufsätze zu Goethes Faust I"),
        (1933, "Aufsätze zu Goethes Faust II"),
        (2044, "Doctor Fausti Weheklag"),
        (2062, "Faust-Variationen"),
        (2235, "Faust"),
        (2350, "파우스트 하나의 비극"),
        (2593, "Ansichten zu Faust"),
        (2604, "Die dramatische Einheit von Goethes Faust"),
        (3294, "파우스트 그는 누구인가?"),
        (3305, "파우스트"),
        (3309, "파우스트"),
        (3314, "Faust - Annäherung an einen Mythos"),
        (3316, "Goethe Faust Zweiter Teil"),
        (3317, "Faust - Der Tragödie zwiter Teil"),
        (3320, "Gustaf Gründgens Faust in Bildern"),
        (3354, "Faust"),
        (3359, "Königs Erläuterungen zu Goethe Faust"),
        (3367, "Erläuterungen zu Goethes Faust Teil2"),
        (3368, "Erläuterungen zu Goethes Faust Teil1"),
        (3374, "Das Volksbuch von Doktor Faust"),
        (3376, "Armin Müller-Stahl, Urfaust"),
        (3405, "Ontologie und Geschichte in Goethes Faust"),
        (3458, "Who is who in Goethes Faust?"),
        (3484, "괴테와 융 파우스트의 분석심리학적 이해"),
        (3487, "파우스트와 빌헬름 마이스터 연구"),
        (3489, "파우스트 연구"),
        (3492, "괴테의 원형 파우스트 & 뷔히너의 보이첵"),
    ],

    "마의 산": [
        (475, "Der Zauberberg 1"),
        (476, "Der Zauberberg 2"),
        (1297, "Der Zauberberg"),
    ],

    # ──────────────────────────────────────────
    # 내용/주제(Content) 쿼리
    # ──────────────────────────────────────────

    "현대 문학": [
        (365, "Film- und Fernsehanalyse"),
        (370, "현대독문학의이해"),
        (630, "Das Drama der Gegenwart"),
        (684, "Gedichte und Interpretationen6 Gegenwart"),
        (764, "Romane des 20. Jahrhunderts 1"),
        (765, "Romane des 20. Jahrhunderts 2"),
        (1378, "Schubumkehr"),
        (1413, "Abenteuer im Wirklichen oder Die Gegenwart unserer Klassiker"),
        (1663, "Panorama des zeitgenössischen Theaters"),
        (1671, "Tendenzen der deutschen Gegenwartsliteratur"),
        (2348, "현대문학이론"),
        (2409, "독일의 현대문학"),
        (2412, "Literatur und Kritik"),
        (2505, "Literatur und Kritik November 2021"),
        (2506, "Literatur und Kritik September 2021"),
        (2507, "Literatur und Kritik Juli 2021"),
        (2508, "Literatur und Kritik Mai 2021"),
        (2509, "Literatur und Kritik März 2021"),
        (2510, "Literatur und Kritik November 2020"),
        (2511, "Literatur und Kritik September 2020"),
        (2512, "Literatur und Kritik Juli 2020"),
        (2513, "Literatur und Kritik November 2019"),
        (2514, "Literatur und Kritik September 2019"),
        (2515, "Literatur und Kritik Juli 2019"),
        (2516, "Literatur und Kritik März 2019"),
        (2517, "Literatur und Kritik November 2018"),
        (2518, "Literatur und Kritik September 2018"),
        (2519, "Literatur und Kritik Juli 2018"),
        (2520, "Literatur und Kritik Mai 2018"),
        (2521, "Literatur und Kritik März 2018"),
        (2522, "Literatur und Kritik September 2017"),
        (2523, "Literatur und Kritik Juli 2017"),
        (2524, "Literatur und Kritik Mai 2017"),
        (2525, "Literatur und Kritik März 2017"),
        (2526, "Literatur und Kritik November 2016"),
        (2527, "Literatur und Kritik September 2016"),
        (2528, "Literatur und Kritik Juli 2016"),
        (2529, "Literatur und Kritik Mai 2015"),
        (2530, "Literatur und Kritik Juli 2015"),
        (2531, "Literatur und Kritik März 2015"),
        (2532, "Literatur und Kritik November 2014"),
        (2533, "Literatur und Kritik September 2014"),
        (2534, "Literatur und Kritik Juli 2014"),
        (2535, "Literatur und Kritik Mai 2014"),
        (2536, "Literatur und Kritik März 2014"),
        (2537, "Literatur und Kritik September 2013"),
        (2538, "Literatur und Kritik September 2007"),
        (2539, "Literatur und Kritik Juli 2007"),
        (2540, "Literatur und Kritik Mai 2006"),
        (2541, "Literatur und Kritik März 2006"),
        (2580, "Deutsches Theater der Gegenwart 2"),
        (2589, "Deutsches Theater der Gegenwart 1"),
        (2608, "Gegenwartsliteratur und Drittes Reich"),
        (2611, "Deutsche Gegenwartsliteratur"),
        (2612, "Zeitkritische Romane des 20. Jahrhunderts"),
        (2614, "Die deutsche Literatur der Gegenwart"),
        (2883, "LITERATUR UND KRITIK 577-578"),
        (2884, "LITERATUR UND KRITIK 579-580"),
        (2885, "LITERATUR UND KRITIK 575-576"),
        (3024, "Gehen"),
        (3909, "Literatur und Gesellschaft in der Bundesrepublik"),
        (4128, "Literatur und Kritik"),
    ],

    "고전 소설": [
        # Goethe novels
        (692, "Die Wahlverwandtschaften"),
        (694, "Götz von Berlichingen"),
        (695, "Iphigenie auf Tauris"),
        (697, "Torquato Tasso"),
        (700, "Wilhelm Meisters Lehrjahre"),
        (942, "Die Leiden des jungen Werther"),
        (995, "Die Wahlverwandtschaften"),
        (1000, "Novelle"),
        (1001, "Novelle"),
        (1002, "Wilhelm Meisters Lehrjahre"),
        (1093, "Faust - Erster und Zweiter Teil"),
        (1094, "Die Leiden des jungen Werther"),
        (1240, "Romane und Novellen 1"),
        (1241, "Romane und Novellen 2"),
        (1242, "Romane und Novellen 3"),
        (2424, "Romane und Novellen 1"),
        (2594, "Die Leiden des jungen Werther Novelle"),
        # Thomas Mann
        (471, "Buddenbrooks"),
        (472, "Lotte in Weimar"),
        (473, "Die Erzählungen Band 1"),
        (474, "Die Erzählungen Band 2"),
        (475, "Der Zauberberg 1"),
        (476, "Der Zauberberg 2"),
        (477, "Mario und der Zauberer"),
        (852, "Tristan"),
        (952, "Tristan"),
        (989, "Mario und der Zauberer"),
        (1005, "Tonio Kröger"),
        (1031, "Der Tod in Venedig"),
        (1297, "Der Zauberberg"),
        (1298, "Der Erwählte / Felix Krull"),
        (1299, "Doktor Faustus"),
        (1302, "Buddenbrooks"),
        # Hermann Hesse
        (1019, "Der Steppenwolf"),
        (1020, "Unterm Rad"),
        (1026, "Der Erwarten"),
        (1027, "Der Steppenwolf"),
        (1029, "Siddharta"),
        (1304, "Peter Camenzind Unterm Rad"),
        (1305, "Gertrud Roßhalde"),
        (1306, "Demian Wanderung"),
        (1307, "Der Steppenwolf"),
        (1308, "Narziß und Goldmund"),
        (1309, "Das Glasperlenspiel I"),
        (1310, "Das Glasperlenspiel II"),
        (1311, "Hermann Hesse Erzählungen 1"),
        (1641, "Narziss und Goldmund"),
        (2426, "Gesammelte Werke 8: Narziß und Goldmund"),
        (2477, "Die Romane und die großen Erzählungen"),
        (3295, "크눌프, 데미안"),
        (3896, "Der Steppenwolf"),
        # Fontane
        (671, "Effi Briest"),
        (672, "Frau Jenny Treibel"),
        (673, "Grete Minde"),
        (674, "Irrungen, Wirrungen"),
        (675, "Schach von Wuthenow"),
        (956, "Effi Briest"),
        (957, "Frau Jenny Treibel"),
        (959, "Irrungen, Wirrungen"),
        (990, "Schach von Wuthenow"),
        (1100, "Effi Briest"),
        (1213, "Der Stechlin"),
        (1214, "Schach von Wuthenow, Irrungen Wirrungen"),
        (1216, "Stine, Frau Jenny Treibel, Effi Briest"),
        # Storm
        (845, "Der Schimmelreiter"),
        (846, "Hans und Heinz Kirch"),
        (847, "Immensee und andere Novellen"),
        (848, "Immensee und andere Novellen"),
        (965, "Der Schimmelreiter"),
        (1008, "Immensee"),
        (1009, "Immensee"),
        (1014, "Hans und Heinz Kirch"),
        (3372, "Immensee"),
        (3652, "Gedichte und Märchen"),
        (3653, "Hans und Heinz Kirch"),
        (3654, "Novellen und Erzählungen"),
        (3657, "Der Schimmelreiter"),
        (3658, "Sämtliche Werke Band I"),
        (3659, "Sämtliche Werke Band II"),
        # Kafka
        (775, "Das Urteil und andere Prosa"),
        (776, "Der Proceß"),
        (777, "Die Verwandlung"),
        (987, "Die Verwandlung"),
        (1023, "Der Prozeß"),
        (1068, "Das Urteil"),
        (1072, "Der Prozeß/Die Verwandlung"),
        (1291, "Das Schloß"),
        (1292, "Amerika"),
        (1293, "Der Prozeß"),
        (1294, "Hochzeitsvorbereitungen auf dem Lande"),
        (1295, "Beschreibung eines Kampfes"),
        # Kleist
        (784, "Das Käthchen von Heilbronn"),
        (789, "Penthesilea"),
        (1284, "Heinrich von Kleist Dramen 1"),
        (1285, "Heinrich von Kleist Dramen 2"),
        # Schiller
        (508, "Dramen"),
        (830, "Kabale und Liebe"),
        (992, "Kabale und Liebe"),
        (1102, "Kabale und Liebe"),
        # Eichendorff
        (622, "Aus dem Leben eines Taugenichts"),
        (665, "Das Marmoldbild Das Schöne Dürande"),
        (1022, "Leben und Taten eines Taugenichts"),
        (1105, "Leben eines Taugenichts"),
        # Hoffmann
        (730, "Das Fräulein von Scuderi"),
        (736, "Klein Zaches genannt Zinnober"),
        (1013, "Klein Zaches genannt Zinnober"),
        (2572, "Fantasiestücke in Callots Manier"),
        (2573, "Nachtstücke"),
        # Grillparzer
        (705, "Der arme Spielmann"),
        (707, "Des Meeres und der Liebe Wellen"),
        (981, "Das goldene Glück und Ende"),
        (1011, "Der arme Spielmann"),
        # Others
        (439, "Grimmelshausen Simplicissimus"),
        (997, "Undine"),
    ],

    "단편 연극": [
        # Brecht
        (446, "Brechts Antigone des Sophokles"),
        (1086, "Der gute Mensch von Sezuan"),
        (1088, "Der gerechte Krieg"),
        (1089, "Der kaukasische Kreidekreis"),
        (1090, "Galilei"),
        (3574, "Stücke"),
        # Schnitzler
        (507, "Reigen Liebelei"),
        # Schiller
        (508, "Dramen"),
        (1281, "SCHILLER GEDICHTE DRAMEN I"),
        (1282, "SCHILLER GEDICHTE DRAMEN II"),
        # Kleist
        (1284, "Heinrich von Kleist Dramen 1"),
        (1285, "Heinrich von Kleist Dramen 2"),
        # Goethe
        (1237, "Dramatische Dichtungen 1"),
        (1238, "Dramatische Dichtungen 2"),
        (1239, "Dramatische Dichtungen 3"),
        # Thomas Bernhard
        (3047, "Die Salzburger Stücke"),
        (3051, "Bernhard Stücke Bd. 1"),
        (3052, "Bernhard Stücke Bd. 1"),
        (3053, "Bernhard Stücke Bd. 2"),
        (3054, "Bernhard Stücke Bd. 2"),
        (3055, "Bernhard Stücke Bd. 3"),
        (3056, "Bernhard Stücke Bd. 3"),
        (3057, "Bernhard Stücke Bd. 4"),
        (3058, "Bernhard Stücke Bd. 4"),
        # Sternheim
        (3569, "Dramen"),
        (3639, "Dramen2"),
        (3640, "Dramen3"),
        # Peter Weiss
        (3862, "Peter Weiss Drei Dramen"),
        (3865, "Peter Weiss Drei Dramen"),
        # Ibsen
        (458, "Dramen"),
        # Dürrenmatt
        (2570, "Komödien 2 und Frühe Stücke"),
        # Bauer
        (2954, "Mikrodramen"),
        # Handke
        (3606, "Prosa Gedichte Theaterstücke"),
        (1635, "Publikumsbeschimpfung und andere Sprechstücke"),
        # Lenz
        (771, "Die Soldaten"),
        # Lessing
        (799, "Emilia Galotti"),
        (800, "Emilia Galotti"),
        (971, "Emilia Galotti"),
        (972, "Emilia Galotti"),
        (1092, "Emilia Galotti"),
        # Dea Loher
        (293, "Diebe"),
        # Schauspielführer / Guides
        (2024, "Knaurs Schauspielführer"),
        # Dramaturgy
        (357, "독일문학작품의 해석 1 <시, 희곡>"),
        (373, "퍼포먼스 드라마투르기"),
    ],

    "사랑 소설": [
        (507, "Reigen Liebelei"),
        (639, "Geschichte vom braven Kasper und dem schönen Annerl"),
        (705, "Der arme Spielmann"),
        (707, "Des Meeres und der Liebe Wellen"),
        (789, "Penthesilea"),
        (830, "Kabale und Liebe"),
        (942, "Die Leiden des jungen Werther"),
        (965, "Der Schimmelreiter"),
        (981, "Das goldene Glück und Ende"),
        (992, "Kabale und Liebe"),
        (997, "Undine"),
        (1011, "Der arme Spielmann"),
        (1094, "Die Leiden des jungen Werther"),
        (2594, "Die Leiden des jungen Werther Novelle"),
        (2630, "Lieben"),
        (3923, "Kabale und Liebe"),
        (4144, "Das verlangen nach Liebe"),
        (4284, "Von Liebe und Schatten"),
    ],

    "모험 소설": [
        (425, "Momo"),
        (439, "Grimmelshausen Simplicissimus"),
        (480, "Durchs Wilde Kurdistan"),
        (551, "Reise- und Abenteuergeschichten"),
        (622, "Aus dem Leben eines Taugenichts"),
        (694, "Götz von Berlichingen"),
        (815, "Das Amulett"),
        (953, "Götz von Berlichingen"),
        (969, "Das Amulett"),
        (1022, "Leben und Taten eines Taugenichts"),
        (1105, "Leben eines Taugenichts"),
        (2391, "모험적 독일인 짐플리치시무스"),
        (2590, "Mio, Mein Mio"),
        (3768, "Fünf Wochen im Ballon"),
        (3769, "Die Kinder des Kapitäns Grant"),
        (3774, "Die geheimnisvolle Insel"),
        (3780, "Meister Antifers wunderbare Abenteuer"),
        (3781, "Zwei Jahre Ferien"),
        (3784, "Die Propellerinsel"),
    ],

    "전쟁 비극": [
        (1358, "Die Generation vor dem Großen Krieg"),
        (2106, "Der Zweite Weltkrieg"),
        (2136, "Das Deutsche Reich und Der Erste Weltkrieg"),
        (2887, "BIBLIOGRAPHIE ZUR DEUTSCHLANDPOLITIK 1941-1974"),
        (3203, "Deutschlands Wiederkehr"),
        (3262, ">>Der Krieg Hat uns Geprägt<< 1"),
        (3263, ">>Der Krieg Hat uns Geprägt<< 2"),
        (3956, "Landschaften eines Krieges - Tschetschenien"),
    ],

    "나치 시대": [
        (218, "Das Nationalsozialistengesetz mit Verbotsgesetz"),
        (264, "나의 투쟁 하"),
        (438, "Die Blechtrommel. Danziger Trilogie 2"),
        (1580, "Protokolle 72/1"),
        (2607, "Die deutsche Literatur im Dritten Reich"),
        (2608, "Gegenwartsliteratur und Drittes Reich"),
        (2851, "Macht Literatur Krieg - Österreichische Literatur im Nationalsozialismus"),
        (2854, "Die österreichische nationalsozialistische Ästhetik"),
        (4045, "Von Caligari zu Hitler"),
        (4060, "Die Namen der Nummern"),
        (4166, "Benedikts Kreuzzug"),
        (4204, "Hitlers Spionin"),
    ],

    "근대 역사": [
        (379, "근대의 세 번역가"),
        (467, "Weimar"),
        (1186, "Gebhardt Handbuch der deutschen Geschichte Band 5"),
        (1191, "Gebhardt Handbuch der deutschen Geschichte Band 10"),
        (1440, "Die 80er Jahre"),
        (1442, "Die 70er Jahre"),
        (2061, "Frühe Neuzeit"),
        (2610, "Die deutsche Literatur in der Weimarer Republik"),
        (2652, "Die Weimarer Republik 1918 1933"),
    ],

    "2차 세계대전": [
        (1616, "Die Rampe 2/82"),
        (2106, "Der Zweite Weltkrieg"),
        (2887, "BIBLIOGRAPHIE ZUR DEUTSCHLANDPOLITIK 1941-1974"),
        (4166, "Benedikts Kreuzzug"),
    ],

    "오스트리아 역사": [
        (249, "Der Herrenstand in Oberösterreich"),
        (250, "Österreichs Aristokratie im Vormärz"),
        (251, "Österreichisches Montanwesen"),
        (363, "오스트리아의 역사와 문화 1"),
        (364, "오스트리아의 역사와 문화 2"),
        (1352, "Zur ersten EU-Präsidentschaft Österreichs 1998 1"),
        (1353, "Zur ersten EU-Präsidentschaft Österreichs 1998 2"),
        (1354, "Zur ersten EU-Präsidentschaft Österreichs 1998 3"),
        (1355, "Zur ersten EU-Präsidentschaft Österreichs 1998 4"),
        (1356, "Studien aus Wien Neue Folge"),
        (1357, "Wien seit 60 Jahren ein Album für die Jugend"),
        (1366, "Das Jüdische Wien"),
        (2163, "Die großen Herrscher des Hauses Habsburg"),
        (2810, "Was ist Wien?"),
        (2812, "Wien 1683 - Die Zweite Türkenbelagerung"),
        (2825, "Vienna"),
        (2830, "Ins unentdeckte Österreich"),
        (2850, "Österreichische Identität in Text und Hypertext"),
        (2854, "Die österreichische nationalsozialistische Ästhetik"),
        (2855, "Komplex Österreich"),
        (3084, "Österreich"),
        (3527, "Rede über Österreich"),
        (3698, "Damals in Wien"),
    ],

    "독일 민법": [
        (76, "독일 민법"),
        (268, "독일 민법"),
    ],

    "독일 통일": [
        (274, "통일 독일의 문화와 예술"),
        (2324, "329일 베를린장벽 붕괴에서 독일통일까지"),
        (2373, "독일통일과 문학"),
        (3296, "독일 통일 한국 통일"),
        (4052, "Wendemanöver - Die geheimen Wege zur Wiedervereinigung"),
    ],

    "현대 독일 정치": [
        (2891, "현대 독일 정치 1"),
        (3898, "현대 독일 정치 2"),
    ],

    "독일 산업": [
        (83, "Die Deutsche Sprache"),
        (216, "Volks-Wirtschafts Lehre"),
        (217, "Einführung in die Allgemeine Betriebswirtschaftslehre"),
        (222, "Die Vierte Industrielle Revolution"),
        (233, "Gesetz über Gesellschaften mit beschränkter Haftung"),
        (239, "Das Weltbild des Kapitalismus"),
        (253, "Wirtschaftspolitik und Arbeitsmarkt"),
        (1399, "Competing Schools of Economic Thought"),
        (2413, "Der Fall Deutschland"),
        (3213, "Data Unser"),
        (3244, "Vertrauen Gewinnt"),
        (3252, "Lukrative Rohstoffmärkte"),
        (3618, "Tatsachen über Deutschland"),
        (3619, "Tatsachen über Deutschland"),
        (3620, "Tatsachen über Deutschland"),
        (3930, "50 Einfache Dinge über unsere Wirtschaft"),
        (3935, "Die 10 Gebote für ein Gesundes Unternehmen"),
        (3974, "Markt und Macht"),
        (4215, "Der Crash des Kapitalismus"),
        (4227, "Betriebswirtschaft konkret"),
        (4228, "Die Basar-Ökonomie"),
    ],

    "독일 국제 관계": [
        (245, "Außenpolitischer Bericht"),
        (2805, "Institutionenführer Österreich - Internationale Beziehungen"),
        (3830, "Inter Nationes"),
    ],

    "언어학개론": [
        (32, "Einführung in die Linguistik"),
        (33, "Lexikon der Sprachwissenschaft"),
        (43, "Einführung in die Semiotik"),
        (83, "Die Deutsche Sprache"),
        (88, "Poetik und Linguistik"),
        (89, "Grammatik, Semantik, Textlinguistik"),
        (100, "Grundzüge der Allgemeinen Sprachwissenschaft"),
        (137, "Grundfragen der Allgemeinen Sprachwissenschaft"),
        (147, "Sprachwissenschaft"),
        (174, "Einführung in die germanistische Linguistik"),
        (212, "Sprache, Wissen und Gesellschaft"),
        (1143, "Lexikon der Sprachwissenschaft (2. Aufl.)"),
        (1144, "Lexikon der Sprachwissenschaft"),
        (3570, "Germanistische Linguistik"),
        (3572, "Studienbuch Linguistik"),
    ],

    "초급 문법": [
        (32, "Einführung in die Linguistik"),
        (74, "Grammatik der deutschen Sprache"),
        (75, "Grammatik der deutschen Sprache"),
        (82, "Einführung in die Grammatik und Orthographie"),
        (86, "ABC der schwachen Verben"),
        (89, "Grammatik, Semantik, Textlinguistik"),
        (132, "Der Satz"),
        (168, "Wir müssen zusammen schreiben!"),
        (180, "Die neue Schulgrammatik"),
        (1119, "Deutsche Grammatik kurz"),
        (2281, "Grammatik der deutschen Sprachen"),
        (2282, "Deutsche Grammatik"),
        (2283, "Kurze deutsche Grammatik für Ausländer"),
        (2284, "ABC der schwachen Verben"),
        (2296, "Deutsch als Fremdsprache1 Grundkurs"),
        (2304, "Test- und Übungsbuch zur deutschen Grammatik"),
        (2318, "Grammatik der modernen deutschen Umgangssprache"),
        (2319, "Lehr- und Übungsbuch der deutschen Grammatik"),
    ],

    "독일어 사전": [
        (8, "Dictionary of 501 German Verbs"),
        (96, "Linguistisches Wörterbuch 1"),
        (97, "Linguistisches Wörterbuch 2"),
        (98, "Linguistisches Wörterbuch 3"),
        (391, "Etymologisches Wörterbuch der deutschen Sprache"),
        (392, "Wörterbuch der Deutschen Sprache"),
        (3580, "German Dictionary"),
        (3600, "독일어변화 사전"),
    ],

    "독일어 인명 사전": [
        (390, "Lexikon deutschsprachiger Schriftsteller"),
        (3302, "독일어권 유학인명록"),
    ],

    "화용론": [
        (116, "Sprachpragmatik"),
        (117, "Sprachpragmatik"),
        (125, "Sprechakte und Sprachfunktionen"),
        (126, "Sprechakte und Sprachfunktionen"),
        (374, "도스토예프스키 장편소설 연구"),
    ],
}
